// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuHtWiKs3KRGkzBvMIcyAp08RWadnk4mc',
    appId: '1:111553451953:web:582bf0494788dd9e01cf90',
    messagingSenderId: '111553451953',
    projectId: 'retina-6dc89',
    authDomain: 'retina-6dc89.firebaseapp.com',
    storageBucket: 'retina-6dc89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxNKNNelVjQJs0ucUSwI2QTsO-ZGbWSEM',
    appId: '1:111553451953:android:2665be8c2540d95e01cf90',
    messagingSenderId: '111553451953',
    projectId: 'retina-6dc89',
    storageBucket: 'retina-6dc89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQZm2MPaMLmp228dQ723goFjIw87fqlhU',
    appId: '1:111553451953:ios:ddd825e6d839e13d01cf90',
    messagingSenderId: '111553451953',
    projectId: 'retina-6dc89',
    storageBucket: 'retina-6dc89.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQZm2MPaMLmp228dQ723goFjIw87fqlhU',
    appId: '1:111553451953:ios:ddd825e6d839e13d01cf90',
    messagingSenderId: '111553451953',
    projectId: 'retina-6dc89',
    storageBucket: 'retina-6dc89.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuHtWiKs3KRGkzBvMIcyAp08RWadnk4mc',
    appId: '1:111553451953:web:6ad3b399d47e2c6101cf90',
    messagingSenderId: '111553451953',
    projectId: 'retina-6dc89',
    authDomain: 'retina-6dc89.firebaseapp.com',
    storageBucket: 'retina-6dc89.firebasestorage.app',
  );
}
