[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd server && npm install --production"]

[phases.build]
cmds = ["echo 'Building server...'", "echo 'Force redeploy'"]

[start]
cmd = "cd server && node index.js"
